name: Eslint Check
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 安装依赖
        run: npm install

      - name: 跑eslint
        run: npx eslint . --ext .js,.jsx,.ts,.vue,.tsx
